---
apiVersion: v1
kind: Service
metadata:
  name: security-service
  labels:
    name: security-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: security-service