---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  labels:
    name: gateway
    type: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate  
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
      - name: gateway
        image: vagrant:5000/sample-microservices-kubernetes-gateway:snapshot-181123-151445-0264
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 2
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 192Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        ports:
        - containerPort: 8080