spring:
  application:
    name: gateway
  profiles:
    active: dev

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  ignored-services: "*-db"
  routes:
    account:
      path: "/account/**"
      serviceId: "account-service"
      strip-prefix: false
  prefix: "/financial-manager"
---

spring:
  profiles: dev
  cloud:
    kubernetes:
      client:
        username: "system:admin"
        password: "admin"
        masterUrl: https://172.28.128.3:6443
        trustCerts: true

---

spring:
  profiles: kubernetes
  cloud:
    kubernetes:
      client:
        trust-certs: true