---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
  labels:
    name: account-service
    type: api
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate  
  template:
    metadata:
      labels:
        name: account-service
    spec:
      containers:
      - name: account-service
        image: vagrant:5000/sample-microservices-kubernetes-account-service:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 2
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 192Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 10
        ports:
        - containerPort: 8080