---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    name: account-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: account-service